# Generated by Django 5.2.7 on 2026-02-18 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        ("recipes", "0002_category_slug_recipe_slug_alter_ingredient_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="recipes.recipe",
            ),
        ),
    ]
