# Generated by Django 5.2.7 on 2026-03-08 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_comment_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="favorite",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
