# Generated by Django 5.2.7 on 2026-01-09 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="instruction",
            unique_together={("recipe", "step_number")},
        ),
    ]
