# Generated by Django 5.2.7 on 2026-03-05 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_category_slug_recipe_slug_alter_ingredient_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipes",
                to="recipes.category",
            ),
        ),
        migrations.RemoveField(
            model_name="subcategory",
            name="category",
        ),
        migrations.AddField(
            model_name="subcategory",
            name="category",
            field=models.ManyToManyField(
                related_name="category", to="recipes.category"
            ),
        ),
    ]
