# Generated by Django 5.2.7 on 2026-01-09 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_alter_instruction_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipe",
            name="followers",
        ),
        migrations.AlterField(
            model_name="favorite",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorites",
                to="recipes.recipe",
            ),
        ),
    ]
