# Generated by Django 5.2.7 on 2026-03-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_alter_recipe_category_remove_subcategory_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=150, null=True, unique=True, verbose_name="url"
            ),
        ),
    ]
