# Generated by Django 5.2.7 on 2026-03-11 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_subcategory_slug"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="instruction",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="instruction",
            name="title",
            field=models.CharField(default=3, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="instruction",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instruction",
                to="recipes.recipe",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="instruction",
            unique_together={("recipe", "step_number", "title")},
        ),
    ]
